version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: user_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    container_name: user_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@postgres:5432/userdb
      SECRET_KEY: ${SECRET_KEY:-your-secret-key-here}
      DEBUG: ${DEBUG:-false}
    depends_on:
      - postgres
    networks:
      - app-network
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge