"""init table

Revision ID: 6cb210dd733e
Revises: 
Create Date: 2025-10-09 13:57:52.422705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cb210dd733e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False, comment='订单ID'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户ID'),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='支付提供商: stripe/alipay/wechat'),
    sa.Column('provider_ref', sa.String(length=200), nullable=True, comment='支付渠道的支付ID'),
    sa.Column('scene', sa.String(length=50), nullable=False, comment='支付场景: qr_code/wap/app等'),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='支付金额'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='货币代码 ISO-4217'),
    sa.Column('refunded_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='已退款金额'),
    sa.Column('refund_count', sa.Integer(), nullable=False, comment='退款次数'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='支付状态: pending/processing/succeeded/failed/canceled/refunding/refunded/partial_refunded'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True, comment='支付完成时间'),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True, comment='取消时间'),
    sa.Column('notify_url', sa.String(length=500), nullable=True, comment='异步通知URL'),
    sa.Column('return_url', sa.String(length=500), nullable=True, comment='同步跳转URL'),
    sa.Column('client_secret', sa.String(length=500), nullable=True, comment='客户端密钥（用于前端调用）'),
    sa.Column('failure_reason', sa.Text(), nullable=True, comment='失败原因'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='扩展元数据'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_created_at', 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=True)
    op.create_index(op.f('ix_payments_provider'), 'payments', ['provider'], unique=False)
    op.create_index(op.f('ix_payments_provider_ref'), 'payments', ['provider_ref'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_index('ix_payments_user_status', 'payments', ['user_id', 'status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='邮箱'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('full_name', sa.String(length=100), nullable=True, comment='全名'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='是否超级管理员'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='最后登录时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('file_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('owner_id', sa.Integer(), nullable=True, comment='归属用户ID（可为空）'),
    sa.Column('storage_type', sa.String(length=16), server_default=sa.text("'local'"), nullable=False, comment='存储类型：local/s3/oss'),
    sa.Column('bucket', sa.String(length=255), nullable=True, comment='存储桶/容器名称'),
    sa.Column('region', sa.String(length=64), nullable=True, comment='区域名（可为空）'),
    sa.Column('key', sa.String(length=512), nullable=False, comment='对象存储中的Key（路径）'),
    sa.Column('unique_key_hash', sa.String(length=64), nullable=False, comment='唯一键哈希：SHA-256(storage_type|bucket|key)'),
    sa.Column('size', sa.BigInteger(), server_default=sa.text('0'), nullable=False, comment='文件大小（字节）'),
    sa.Column('etag', sa.String(length=64), nullable=True, comment='存储返回的ETag/校验值'),
    sa.Column('content_type', sa.String(length=100), nullable=True, comment='MIME类型'),
    sa.Column('original_filename', sa.String(length=255), nullable=True, comment='原始文件名'),
    sa.Column('kind', sa.String(length=50), nullable=True, comment='业务分类，如 avatar/document'),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否公共可读'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='扩展元数据（JSON）'),
    sa.Column('url', sa.String(length=1024), nullable=True, comment='公共/CDN URL快照（可选）'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False, comment='文件状态：pending/active/deleted'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间（软删除）'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_key_hash'),
    comment='文件资源表，记录对象存储中的文件元数据'
    )
    op.create_index('ix_file_assets_created_at', 'file_assets', ['created_at'], unique=False)
    op.create_index('ix_file_assets_owner_created', 'file_assets', ['owner_id', 'created_at'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False, comment='令牌唯一标识符'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('family_id', sa.String(length=64), nullable=False, comment='令牌家族ID，同一登录会话共享'),
    sa.Column('parent_jti', sa.String(length=64), nullable=True, comment='父令牌JTI，用于追踪令牌链'),
    sa.Column('token_hash', sa.String(length=128), nullable=False, comment='令牌SHA-256哈希'),
    sa.Column('is_revoked', sa.Boolean(), nullable=False, comment='是否已撤销'),
    sa.Column('is_used', sa.Boolean(), nullable=False, comment='是否已使用（轮转后标记）'),
    sa.Column('device_info', sa.Text(), nullable=True, comment='设备信息（User-Agent等）'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP地址（支持IPv6）'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='过期时间'),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True, comment='使用时间'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='撤销时间'),
    sa.Column('revoke_reason', sa.String(length=200), nullable=True, comment='撤销原因'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_created_at'), 'refresh_tokens', ['created_at'], unique=False)
    op.create_index('ix_refresh_tokens_expires', 'refresh_tokens', ['expires_at', 'is_revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('ix_refresh_tokens_family_active', 'refresh_tokens', ['family_id', 'is_revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_is_revoked'), 'refresh_tokens', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_parent_jti'), 'refresh_tokens', ['parent_jti'], unique=False)
    op.create_index('ix_refresh_tokens_user_active', 'refresh_tokens', ['user_id', 'is_revoked', 'is_used'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False, comment='关联的支付ID'),
    sa.Column('order_id', sa.String(length=100), nullable=False, comment='订单ID'),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='支付提供商'),
    sa.Column('provider_refund_id', sa.String(length=200), nullable=True, comment='渠道退款ID'),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='退款金额'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='货币代码'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='退款状态: pending/processing/succeeded/failed'),
    sa.Column('reason', sa.Text(), nullable=True, comment='退款原因'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('succeeded_at', sa.DateTime(timezone=True), nullable=True, comment='退款成功时间'),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True, comment='退款失败时间'),
    sa.Column('failure_reason', sa.Text(), nullable=True, comment='失败原因'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='扩展元数据'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_created_at'), 'refunds', ['created_at'], unique=False)
    op.create_index(op.f('ix_refunds_id'), 'refunds', ['id'], unique=False)
    op.create_index('ix_refunds_order_id', 'refunds', ['order_id'], unique=False)
    op.create_index(op.f('ix_refunds_payment_id'), 'refunds', ['payment_id'], unique=False)
    op.create_index('ix_refunds_payment_status', 'refunds', ['payment_id', 'status'], unique=False)
    op.create_index(op.f('ix_refunds_provider_refund_id'), 'refunds', ['provider_refund_id'], unique=False)
    op.create_index(op.f('ix_refunds_status'), 'refunds', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refunds_status'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_provider_refund_id'), table_name='refunds')
    op.drop_index('ix_refunds_payment_status', table_name='refunds')
    op.drop_index(op.f('ix_refunds_payment_id'), table_name='refunds')
    op.drop_index('ix_refunds_order_id', table_name='refunds')
    op.drop_index(op.f('ix_refunds_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_created_at'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_user_active', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_parent_jti'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_is_revoked'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_family_active', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_expires', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_created_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_file_assets_owner_created', table_name='file_assets')
    op.drop_index('ix_file_assets_created_at', table_name='file_assets')
    op.drop_table('file_assets')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_payments_user_status', table_name='payments')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_ref'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index('ix_payments_created_at', table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
